### ISSUE TITLE
pyodide-kernel on Xeus

### ISSUE THREAD

**Issue by MRYingLEE** [jupyterlite/pyodide-kernel#119]
I am using a few Jupyterlite kernels, such as Xeus-Javascript and pyodide (non-Xeus-based）.

According to Jupyterlite documents, a Xeus based kernel has a much simpler implementation requirement. Just curious, why don't you migrate Pyodide to Xeus architecture. So that the code base is much smaller and easy to maintenance.

Just for your reference.

**Comment by bollwyvl** [comment]
> Why don't you?

Why don't you?

To my knowledge, no `xeus` kernel a way to dynamically install and import libraries not downloaded and packed at site build time, so a PR that did, somehow, port `pyodide` to the `xeus` architecture would quickly find a number of limitations.
