### ISSUE TITLE
Unable to change pyodideUrl via json configuration file

### ISSUE THREAD

**Issue by lesteve** [jupyterlite/pyodide-kernel#44]
## Description

I am trying to set the version of Pyodide via a json configuration file but it does not seem like this is taken into account.

On the other hand, it seem to work fine by editing directly `_output/jupyter-lite.json` and adding `pyodideUrl` there.

## Reproduce

Following https://jupyterlite.readthedocs.io/en/latest/howto/pyodide/pyodide.html here is my `jupyter_lite_config.json` to use 0.23.1 instead of the default 0.23:
```json
{
  "jupyter-lite-schema-version": 0,
  "jupyter-config-data": {
    "litePluginSettings": {
      "@jupyterlite/pyodide-kernel-extension:kernel": {
        "pyodideUrl": "https://cdn.jsdelivr.net/pyodide/v0.23.1/full/pyodide.js"
      }
    }
  }
} 
```

The config seems to be taken into account:
```
jupyter lite build --Application.show_config=True
```
```
Loaded config files:
  /tmp/jupyter_lite_config.json

jupyter-config-data
  .litePluginSettings = {   '@jupyterlite/pyodide-kernel-extension:kernel': {   'pyodideUrl': 'https://cdn.jsdelivr.net/pyodide/v0.23.1/full/pyodide.js'}}
```

Then I build:
```
jupyter lite build
```

but `_output/jupyter-lite.json` does not have my custom `pyodideUrl`.

## Expected behavior

`pyodideUrl` is in `_output/jupyter-lite.json`

## Context

- JupyterLite version: 0.1.0
- jupyterlite-pyodide-kernel 0.0.6

**Comment by jtpio** [comment]
Thanks @lesteve for the report.

> is my `jupyter_lite_config.json`

Shouldn't it be `jupyter-lite.json`?

Looks like the docs page doesn't mention it, maybe we should add it so it's more clear.

**Comment by lesteve** [comment]
> Shouldn't it be jupyter-lite.json?

Not sure, I think I have tried both `jupyter-lite.json` and `jupyter_lite_config.json` and also passing explicitly the config with `--config` and did not manage to make it work ...

**Comment by jtpio** [comment]
I just tried with the following:

- `jupyterlite-pyodide-kernel==0.0.6`: the latest at the moment, still on 0.23.0
- `jupyter-lite.json`  with the following:

```json
{
  "jupyter-lite-schema-version": 0,
  "jupyter-config-data": {
    "litePluginSettings": {
      "@jupyterlite/pyodide-kernel-extension:kernel": {
        "pyodideUrl": "https://cdn.jsdelivr.net/pyodide/v0.23.1/full/pyodide.js"
      }
    }
  }
} 
```
- `jupyter lite build`
- `python -m http.server --directory _output

And it seems to pick up the version correctly:

![image](https://user-images.githubusercontent.com/591645/233405086-ff4a705c-2025-4327-a429-14d887af1ede.png)

**Comment by jtpio** [comment]
@lesteve have you tried cleaning up the local cache and previous `_output` folder just to be sure it's not an issue with previous runs still being cached?

**Comment by lesteve** [comment]
OK weird, it seems to be working now indeed. I am pretty sure I did try `rm -rf _output` or `--force` because I suspected there may be some caching issues but maybe I tried too many things ...

**Comment by jtpio** [comment]
Thanks for checking :+1: 

If you feel like opening a PR to the JupyterLite docs to mention the `jupyter-lite.json` file that would be greatly appreciated, thanks! Otherwise no problem.

**Comment by jtpio** [comment]
Opened https://github.com/jupyterlite/jupyterlite/pull/1059 to not forget about it :)
