### ISSUE TITLE
Option "Using a custom Pyodide distribution" (specified in `jupyter-lite.json`) not working

### ISSUE THREAD

**Issue by michaelweinold** [jupyterlite/pyodide-kernel#59]
## Description

Even though I specify the most recent version of `pyodide==0.24.0` in the `jupyter-lite.json` file, as per the [JupyterLite Documentation: "Using a custom Pyodide distribution"](https://jupyterlite.readthedocs.io/en/latest/howto/pyodide/pyodide.html#using-a-custom-pyodide-distribution):

```json
{
  "jupyter-lite-schema-version": 0,
  "jupyter-config-data": {
    "disabledExtensions": [
      "@jupyterlab/drawio-extension",
      "jupyterlab-kernel-spy",
      "jupyterlab-tour"
    ],
    "@jupyterlite/pyodide-kernel-extension:kernel": {
      "pyodideUrl": "https://cdn.jsdelivr.net/pyodide/v0.24.0/full/pyodide.js"
    },
  }
}
```

and the site build from the GH actions workflow

```
- name: Build the JupyterLite site
        run: |
          cp README.md content
          jupyter lite build --contents content --output-dir dist
```

completes successfully, the `pyodide` version does not change from the default `0.23.4` shipped with `jupyterlite-pyodide-kernel==0.1.1`:

```python
A WebAssembly-powered Python kernel backed by Pyodide
import pyodide
pyodide.__version__
'0.23.4'
import pyodide_kernel
pyodide_kernel.__version__
'0.1.1'
```

Is there another way to specify the exact version of Pyodide during the build?

## Reproduce

Specify pyodide=0.24.0 in the 

1. Use the above `.json` config file in a fork of the [JupyterLite demo](https://github.com/jupyterlite/demo).

## Expected behavior

The most recent version of `pyodide` is used.

## Context

- JupyterLite version: `jupyterlite-core==0.1.2`
- Operating System and version: GH actions platform
- Browser and version: various (Safari Version 16.6 (18615.3.12.11.2), Chrome Version 116.0.5845.110 (Official Build) (arm64))

<details><summary>Browser Output</summary>
<pre>
remoteEntry.a37e37c87d212fe85e13.js:1 Unsatisfied version 1.37.1 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @lumino/widgets (required ^2.0.1)
p @ remoteEntry.a37e37c87d212fe85e13.js:1
remoteEntry.a37e37c87d212fe85e13.js:1 Unsatisfied version 1.10.3 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @lumino/messaging (required ^2.0.0)
p @ remoteEntry.a37e37c87d212fe85e13.js:1
remoteEntry.a37e37c87d212fe85e13.js:1 Unsatisfied version 1.12.1 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @lumino/coreutils (required ^2.0.0)
p @ remoteEntry.a37e37c87d212fe85e13.js:1
remoteEntry.a37e37c87d212fe85e13.js:1 Unsatisfied version 1.11.1 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @lumino/signaling (required ^2.0.0)
p @ remoteEntry.a37e37c87d212fe85e13.js:1
remoteEntry.a37e37c87d212fe85e13.js:1 Unsatisfied version 1.9.2 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @lumino/algorithm (required ^2.0.0)
p @ remoteEntry.a37e37c87d212fe85e13.js:1
remoteEntry.a37e37c87d212fe85e13.js:1 Unsatisfied version 3.5.3 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/translation (required ^4.0.5)
p @ remoteEntry.a37e37c87d212fe85e13.js:1
remoteEntry.a37e37c87d212fe85e13.js:1 Unsatisfied version 3.5.3 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/settingregistry (required ^4.0.5)
p @ remoteEntry.a37e37c87d212fe85e13.js:1
remoteEntry.a37e37c87d212fe85e13.js:1 Unsatisfied version 3.5.3 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/notebook (required ^4.0.5)
p @ remoteEntry.a37e37c87d212fe85e13.js:1
remoteEntry.a37e37c87d212fe85e13.js:1 Unsatisfied version 6.5.3 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/services (required ^7.0.5)
p @ remoteEntry.a37e37c87d212fe85e13.js:1
remoteEntry.a37e37c87d212fe85e13.js:1 Unsatisfied version 1.8.2 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @lumino/properties (required ^2.0.0)
p @ remoteEntry.a37e37c87d212fe85e13.js:1
remoteEntry.a37e37c87d212fe85e13.js:1 No satisfying version (^4.0.5) of shared module @jupyterlab/outputarea found in shared scope default.
Available versions: 3.5.3 from _JUPYTERLAB.CORE_OUTPUT
p @ remoteEntry.a37e37c87d212fe85e13.js:1
remoteEntry.a37e37c87d212fe85e13.js:1 Unsatisfied version 3.5.3 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/logconsole (required ^4.0.5)
p @ remoteEntry.a37e37c87d212fe85e13.js:1
remoteEntry.a37e37c87d212fe85e13.js:1 Unsatisfied version 3.5.3 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/rendermime (required ^4.0.5)
p @ remoteEntry.a37e37c87d212fe85e13.js:1
remoteEntry.a37e37c87d212fe85e13.js:1 Unsatisfied version 1.10.4 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @lumino/disposable (required ^2.0.0)
p @ remoteEntry.a37e37c87d212fe85e13.js:1
remoteEntry.a37e37c87d212fe85e13.js:1 Unsatisfied version 3.5.3 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/mainmenu (required ^4.0.5)
p @ remoteEntry.a37e37c87d212fe85e13.js:1
remoteEntry.b15a25cb741a6c7381f8.js:1 Unsatisfied version 1.37.1 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @lumino/widgets (required ^2.0.1)
s @ remoteEntry.b15a25cb741a6c7381f8.js:1
remoteEntry.6a76d3e37f02d3977b44.js:1 Unsatisfied version 3.5.3 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/apputils (required ^4.0.0)
d @ remoteEntry.6a76d3e37f02d3977b44.js:1
remoteEntry.6a76d3e37f02d3977b44.js:1 Unsatisfied version 1.9.2 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @lumino/algorithm (required ^2.0.0)
d @ remoteEntry.6a76d3e37f02d3977b44.js:1
remoteEntry.6a76d3e37f02d3977b44.js:1 Unsatisfied version 1.37.1 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @lumino/widgets (required ^2.0.1)
d @ remoteEntry.6a76d3e37f02d3977b44.js:1
remoteEntry.6a76d3e37f02d3977b44.js:1 Unsatisfied version 3.5.3 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/ui-components (required ^4.0.0)
d @ remoteEntry.6a76d3e37f02d3977b44.js:1
remoteEntry.ade722230aea9b7793b2.js:1 Unsatisfied version 1.37.1 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @lumino/widgets (required ^1.37.2)
u @ remoteEntry.ade722230aea9b7793b2.js:1
remoteEntry.edc72ee71d4ec67598f6.js:1 Unsatisfied version 1.37.1 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @lumino/widgets (required ^1.37.2)
s @ remoteEntry.edc72ee71d4ec67598f6.js:1
remoteEntry.d50eb71a2b1d4b9ee0b9.js:1 Unsatisfied version 1.37.1 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @lumino/widgets (required ^1.37.2)
s @ remoteEntry.d50eb71a2b1d4b9ee0b9.js:1
service-manager.ts:50 Registering new JupyterLite ServiceWorker https://michaelweinold.github.io/jl_pyodide_test/service-worker-f7de73d.js
service-manager.ts:52 JupyterLite ServiceWorker was sucessfully registered
index.ts:235 Kernel filesystem and JupyterLite contents will be synced
index.js:51 Pyodide contents will be synced with Jupyter Contents
pyodide.asm.js:9 Loading micropip, packaging
pyodide.asm.js:9 Loaded packaging, micropip
pyodide.asm.js:9 Loading sqlite3
pyodide.asm.js:9 Loaded sqlite3
pyodide.asm.js:9 Loading decorator, jedi, parso, pygments, six
pyodide.asm.js:9 Loaded decorator, six, parso, jedi, pygments
</pre>
</details>

**Comment by michaelweinold** [comment]
Hey, @jtpio - sorry for the quick ping. I would greatly appreciate it if you could have a quick look. Is this something that needs to be fixed in either the pyodide-kernel or jupyterlite?

I [added a package to pyodide back in June](https://github.com/pyodide/pyodide/pull/3897), which was only now included in the 0.24.0 release - I'd very much like to demo that at [our conference](http://brightcon.link) next week. If would be very helpful for me to find out if I will be able to use the latest version of pyodide within a JupyterLite environment by then.

**Comment by jtpio** [comment]
@michaelweinold normally the config option as specified in the top comment should do the trick.

But we could also update the Pyodide version in this repo and make a new release. Would you like to open a PR? The diff would be similar to https://github.com/jupyterlite/pyodide-kernel/pull/50.

Thanks!

**Comment by jtpio** [comment]
Maybe there is still an issue with the config option that would have to be fixed anyway (would need to check).

**Comment by bollwyvl** [comment]
`micropip` also changed a lot. #62 is open as an alternative, exploring the changes. Mostly seems to work locally, we'll see what CI says.

**Comment by michaelweinold** [comment]
> Maybe there is still an issue with the config option that would have to be fixed anyway (would need to check).

It would seem so, @jtpio - I tried again with:

```json
{
    "jupyter-lite-schema-version": 0,
    "jupyter-config-data": {
        "settingsStorageDrivers": ["asyncStorage"],
        "contentsStorageDrivers": ["asyncStorage"],
        "litePluginSettings": {
            "@jupyterlite/pyodide-kernel-extension:kernel": {
                "pyodideUrl": "https://cdn.jsdelivr.net/pyodide/v0.26.2/full/pyodide.js"
            },
        },
    },
}
```

But I still get:

<img width="587" alt="Screenshot 2024-07-30 at 08 34 06" src="https://github.com/user-attachments/assets/366d0291-db42-4d3e-9436-a0b3e2fa02df">

The GH Actions build log also does not tell me which version was ultimately used.

**Comment by jtpio** [comment]
@michaelweinold could it be because this JSON snippet contains trailing commas ?

I just tried in a clean folder with `jupyterlite-core==0.4.0` and `jupyterlite-pyodide-kernel==0.4.0` and it seems to be working fine:

```json
{
    "jupyter-lite-schema-version": 0,
    "jupyter-config-data": {
        "settingsStorageDrivers": ["asyncStorage"],
        "contentsStorageDrivers": ["asyncStorage"],
        "litePluginSettings": {
            "@jupyterlite/pyodide-kernel-extension:kernel": {
                "pyodideUrl": "https://cdn.jsdelivr.net/pyodide/v0.26.2/full/pyodide.js"
            }
        }
    }
}
```

![image](https://github.com/user-attachments/assets/03c9bc65-37ba-4735-aad5-2c8abe06f749)

**Comment by jtpio** [comment]
> could it be because this JSON snippet contains trailing commas ?

If that's the case and it fixes your issue, maybe the `jupyter lite build` process should validate the `jupyter-lite.json` if it exists, and error out if it can't be parsed correctly.

**Comment by michaelweinold** [comment]
...it _was_ the trailing commas. Having removed them:

```json
{
    "jupyter-lite-schema-version": 0,
    "jupyter-config-data": {
        "settingsStorageDrivers": ["asyncStorage"],
        "contentsStorageDrivers": ["asyncStorage"],
        "litePluginSettings": {
            "@jupyterlite/pyodide-kernel-extension:kernel": {
                "pyodideUrl": "https://cdn.jsdelivr.net/pyodide/v0.26.2/full/pyodide.js"
            }
        }
    }
}
```

Gives me the correct Pyodide version:

<img width="1728" alt="Screenshot 2024-07-30 at 11 04 38" src="https://github.com/user-attachments/assets/483f4223-4c67-4b41-863a-ffa6cf80273b">

**Comment by jtpio** [comment]
Thanks @michaelweinold for checking :+1: 

I opened https://github.com/jupyterlite/jupyterlite/issues/1447 to improve this in the `jupyter lite build` process.
