### ISSUE TITLE
OpenAI /TCP support

### ISSUE THREAD

**Issue by MRYingLEE** [jupyterlite/pyodide-kernel#75]
I am testing OpenAI python code with Jupyterlite Pyodide kernel.

I met the following error:

MaxRetryError: HTTPSConnectionPool(host='...', port=443): Max retries exceeded with url: /openai/deployments/gpt-35-turbo/chat/completions?api-version=2023-07-01-preview (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x64f9110>: Failed to establish a new connection: [Errno 50] Protocol not available'))

I am confused. Does it mean TCP (port=443) is not supported? So OpenAI is not supported definitely.

Please clarify.

**Comment by MRYingLEE** [comment]
Pyodide, or anything running in a web browser, does not support TCP/IP connections. 

According to https://stackoverflow.com/questions/71789778/modulenotfounderror-no-module-named-psycopg2-by-using-pyodide#:~:text=Pyodide%2C%20or%20anything%20running%20in%20a%20web%20browser%2C,normal%20SQL%20database%20driver%20cannot%20work%20with%20Pyodide.

So I am closing this issue.

**Comment by rth** [comment]
>  does not support TCP/IP connections.

HTTPS is the exception, you should be able to access other web pages from your application, assuming the library is patched to use JavaScript fetch for the browser which [pyodide-http](https://github.com/koenvo/pyodide-http) does. So you need to use pyodide-http, unless the download is done with a library not yet supported there.
