### ISSUE TITLE
Enable Python tests for the addon

### ISSUE THREAD

**Issue by jtpio** [jupyterlite/pyodide-kernel#9]
### Problem

Follow-up to #2

Currently the Python tests have been disabled: https://github.com/jupyterlite/pyodide-kernel/blob/9d3ee654db277011b0dea9280aa1ec192ffd4e8c/.github/workflows/test.yml#L39-L42

Because the released `jupyterlite` provides the same addons and creates conflicts.

### Proposed Solution

Re-enable these tests. 

### Additional context

This might have to happen a bit later after completing https://github.com/jupyterlite/jupyterlite/pull/854.

**Comment by bollwyvl** [comment]
On #8, pulling in the hot wheel from https://github.com/jupyterlite/jupyterlite/pull/854

Turns out, having the tests run would have been _great_, as it wasn't really set up to handle federated `wheelDir`s yet which lead to a lot of thrashing on my end.
