### ISSUE TITLE
Release 0.3.0

### ISSUE THREAD

**Issue by bollwyvl** [jupyterlite/pyodide-kernel#99]
### Problem

[`jupyterlite-core 0.3.0`](https://pypi.org/project/jupyterlite-core/0.3.0/) is out, but it is unlikely the `0.2.0` line will work with it.

### Proposed Solution

Get a release out soon.

#### `pyodide-lock.json`

It would be good to accommodate the intent of #49 in the 0.3.0 line, but likely not as it stands, and should expose more of the `loadPyodide` options. I'll try to get a PR up presently with a concrete proposal of how we might add some flexibility without incurring too much complexity here, with a follow-on (either on this repo or another) that could do much more with that information.

**Comment by jtpio** [comment]
> [`jupyterlite-core 0.3.0`](https://pypi.org/project/jupyterlite-core/0.3.0/) is out, but it is unlikely the `0.2.0` line will work with it.

Normally it should be compatible, there are not many changes in `jupyterlite-core==0.3.0` apart from the JupyterLab and Notebook updates. Maybe we could loosen the pins to allow for install `jupyterlite-pyodide-kernel` with multiple JupyterLite versions in the long run.

In the meantime I'll open a PR to do the update and follow-up with a release.

**Comment by jtpio** [comment]
> Of note, I almost have the `loadPyodideOptions` PR ready, and would rather see that land on `0.3.0` than some later release, but am presently a bit blocked waiting for the releases to hit conda-forge CDN.

Thanks for handling the conda-forge updates :+1: 

Could the `loadPyodideOptions` change be released in a `0.4.0` pre-release? We don't have to follow the same versions as `jupyterlite-core` for `jupyterlite-pyodide-kernel` (meaning we can release more if needed)

**Comment by bollwyvl** [comment]
I see we're all good. Thanks!
